[package]
name = "pathfind-2d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7.0"
glam = "*"
mint = "0.5.9"
rand = "*"
serde = { version = "1.0.*", features = ["derive"]}